Finish ShooterSubsystem
robototes/TrainingRepo2021 pull request #7
Opened 2021-12-14 05:46 UTC by jamietheraccoon

Added PID controllers to the ShooterSubsystem and inverted one of the motors to clean up the code

2022-01-18 05:06 UTC, jamesdooley4 requested changes
Please fix the typo in the drive base subsystem name

2022-01-18 05:06 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/DrivebaseSubsytem.java
> +public class DrivebaseSubsytem extends SubsystemBase implements Loggable{
Please rename the file & class to fix the typo: DrivebaseSubsytem  ->  DrivebaseSubsystem

2022-01-18 05:06 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/ShooterSubsystem.java
> +        this.rightMotor.setInverted(true);
Best to also set the motors to coast mode, else they're likely going to be damaged or draw a lot of current when they are set to stop after running at high speed.

2022-01-19 22:27 UTC, jamietheraccoon commented
Implemented suggested changes

2022-01-19 22:31 UTC, jbko6 commented
good job

2022-01-20 03:12 UTC, jamesdooley4 approved these changes

2022-01-20 03:12 UTC, merged